// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYVx_1uEuVjlfg1XRy8Jf5EH4Rvc5wXEw',
    appId: '1:461793458589:web:f9d29809b26e1ff8d71774',
    messagingSenderId: '461793458589',
    projectId: 'my-lms-k4',
    authDomain: 'my-lms-k4.firebaseapp.com',
    storageBucket: 'my-lms-k4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YlaTm16dfOq2-IPcfY11NeS1Jb9Szuw',
    appId: '1:461793458589:android:5959aa446b94528bd71774',
    messagingSenderId: '461793458589',
    projectId: 'my-lms-k4',
    storageBucket: 'my-lms-k4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNcQTZ38L7dmOZr0e4rSZweXpRHx4_GM',
    appId: '1:461793458589:ios:974ed62a31702b06d71774',
    messagingSenderId: '461793458589',
    projectId: 'my-lms-k4',
    storageBucket: 'my-lms-k4.appspot.com',
    iosClientId: '461793458589-tvoljpts02pr3t1ahdrigo8b48lkvs4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwNcQTZ38L7dmOZr0e4rSZweXpRHx4_GM',
    appId: '1:461793458589:ios:2abc802808f5f0e2d71774',
    messagingSenderId: '461793458589',
    projectId: 'my-lms-k4',
    storageBucket: 'my-lms-k4.appspot.com',
    iosClientId: '461793458589-pu19o7gnpijkfjttbagah7p9kjduvf2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.lms.RunnerTests',
  );
}
